version: '3.6'
services:
  Elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
    volumes:
    - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node    
    ports:
    - '9200:9200'
    - '9300:9300'
    networks:
      - elk

  Logstash:
    image: logstash:7.16.2
    container_name: logstash
    restart: always
    volumes:
    - ./logstash/:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf 
    depends_on:
      - Elasticsearch
    ports:
    - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"    
    networks:
      - elk

  Kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: always       
    ports:
    - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200  
    depends_on:
      - Elasticsearch  
    networks:
      - elk

  logserver:
    build: ./striide-log-server # Assuming the Dockerfile is in the ./log-server directory
    container_name: logserver
    ports:
      - "4001:4001"   # Assuming your server runs on port 4001
    environment:
      - LOG_LEVEL=debug
    networks:
      - elk
    depends_on:
      - Logstash    # Ensure LogServer is up before Logstash starts
    volumes:
      - ./logs:/logs  # Mounts the host './logs' directory to '/logs' in the container

volumes:
  elastic_data: {}  # Volume for Elasticsearch data

networks:
  elk:
    driver: bridge