apiVersion: v1
kind: Service
metadata:
  name: striide-frontend
spec:
  selector:
    app: striide-frontend
  ports:
    - protocol: TCP
      port: 3000  # The port the service will be exposed on inside the cluster
      targetPort: 3000  # The port inside the container
      nodePort: 30000   # The external port you can access on your machine
  type: NodePort  # Exposes the service externally
