apiVersion: apps/v1
kind: Deployment
metadata:
  name: striide-frontend
  labels:
    app: striide-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: striide-frontend
  template:
    metadata:
      labels:
        app: striide-frontend
    spec:
      containers:
        - name: striide-frontend
          image: vineexoxo/striide-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_BACKEND_URL
              value: "localhost:8080" # Update this URL as needed
