apiVersion: v1
kind: Service
metadata:
  name: striide-frontend
spec:
  selector:
    app: striide-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
  type: NodePort
