---
# 1. Stop all running containers
- name: Stop all Docker containers
  ansible.builtin.shell: docker stop $(docker ps -q)
  ignore_errors: yes  # Ignore errors if no containers are running

# 2. Remove all stopped containers
- name: Remove all Docker containers
  ansible.builtin.shell: docker rm $(docker ps -a -q)
  ignore_errors: yes  # Ignore errors if no containers exist

# 3. Remove all Docker images
- name: Remove all Docker images
  ansible.builtin.shell: docker rmi $(docker images -q)
  ignore_errors: yes  # Ignore errors if no images exist

# 4. Prune unused Docker resources
- name: Prune unused Docker resources
  ansible.builtin.shell: docker system prune -f --volumes
  ignore_errors: no
