name: CICD Pipeline

on:
  push:
    branches:
      - terraform # Trigger on push to main branch

jobs:

  initialise:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3
  

  build_backend:
    runs-on: ubuntu-latest
    needs: initialise

    steps:
    #check code
      - name: Checkout code
        uses: actions/checkout@v3

      #login dockerhub
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: 'vineexoxo'
          DOCKER_PASSWORD: 'Dockerina1'
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      # Step 3: Build Backend Docker image
      - name: Build Backend Docker image
        run: |
          cd striide-backend
          docker build -t vineexoxo/striide-backend:latest .

      # Step 4: Push Backend Docker image to Dockerhub
      - name: Push striide-backend to Dockerhub
        run: docker push vineexoxo/striide-backend:latest

      # Step 5: Clean up Backend Docker image
      - name: Clean up Docker images
        run: |
          docker rmi vineexoxo/striide-backend:latest || true
    

  build_frontend:
    runs-on: ubuntu-latest
    needs: initialise

    steps:
        #check code
      - name: Checkout code
        uses: actions/checkout@v3

      #login dockerhub
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: 'vineexoxo'
          DOCKER_PASSWORD: 'Dockerina1'
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      # Step 5: Build Frontend Docker image
      - name: Build Frontend Docker image
        run: |
          cd striide-frontend
          docker build -t vineexoxo/striide-frontend:latest .

      # Step 6: Push Frontend Docker image to Dockerhub
      - name: Push striide-frontend to Dockerhub
        run: docker push vineexoxo/striide-frontend:latest

      # Step 7: Clean up Backend Docker image
      - name: Clean up Docker images
        run: |
          docker rmi vineexoxo/striide-frontend:latest || true


  deploy_backend:
    needs: build_backend
    runs-on: ubuntu-latest

    steps:
      # Step 1: Pull Backend Docker Image
      - name: Pull Backend Docker Image
        run: sudo docker pull vineexoxo/striide-backend:latest

      # Step 2: Delete old Backend Docker Container (if exists)
      - name: Delete old Backend Docker Container
        run: sudo docker rm -f striide-backend-container || true

      # Step 3: Run Backend Docker Container
      - name: Run Backend Docker Container
        env:
          ROCKET_DATABASES: ${{ secrets.ROCKET_DATABASES }}
          ENV: ${{ secrets.ENV }}
          XATA_API_KEY: ${{ secrets.XATA_API_KEY }}
        run: |
          sudo docker run -d \
            --name striide-backend-container \
            -p 8000:8080 \
            -e ROCKET_DATABASES='{postgres={url="postgresql://cb2s42:xau_1d9LHuNg9qIh0dpuA14x1URryIQ5soOr3@us-east-1.sql.xata.sh/striide:main?sslmode=require", max_connections=1024}}' \
            -e ENV='development' \
            -e XATA_API_KEY='xau_1d9LHuNg9qIh0dpuA14x1URryIQ5soOr3' \
            vineexoxo/striide-backend:latest


  deploy_frontend:
    needs: build_frontend
    runs-on: ubuntu-latest

    steps:
      # Step 1: Pull Frontend Docker Image
      - name: Pull Frontend Docker Image
        run: sudo docker pull vineexoxo/striide-frontend:latest

      # Step 2: Delete old Frontend Docker Container (if exists)
      - name: Delete old Frontend Docker Container
        run: sudo docker rm -f striide-frontend-container || true

      # Step 3: Run Frontend Docker Container
      - name: Run frontend Docker container
        env:
          NEXT_PUBLIC_MAPBOX_TOKEN: 'pk.eyJ1Ijoic3RyaWlkZSIsImEiOiJjbTQxaXh2ZmoyYzlwMmpxeno5YXR6cmxvIn0.pk3E4tHYcOWCNhuhwzNAiA'
          NEXT_PUBLIC_MAPBOX_MAP_STYLE: 'mapbox://styles/striide/clyorf2ms024e01p81gy3577s'
          NEXT_PUBLIC_API_URL: 'https://striide-45qob5kdnq-ue.a.run.app'
          NEXT_PUBLIC_SEARCH_API_SESSION_TOKEN: '56fb4ac0-34e4-46df-b6a9-a6c86eb68ec3'
          NEXT_PUBLIC_BACKEND_URL: 'http://127.0.0.1:8000'
        run: |
          sudo docker run -d \
            --name striide-frontend-container \
            -e NEXT_PUBLIC_MAPBOX_TOKEN=$NEXT_PUBLIC_MAPBOX_TOKEN \
            -e NEXT_PUBLIC_MAPBOX_MAP_STYLE=$NEXT_PUBLIC_MAPBOX_MAP_STYLE \
            -e NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL \
            -e NEXT_PUBLIC_SEARCH_API_SESSION_TOKEN=$NEXT_PUBLIC_SEARCH_API_SESSION_TOKEN \
            -e NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL \
            -p 3000:3000 \
            vineexoxo/striide-frontend:latest

  start_ELK_LOG_SERVER:
    needs: 
      - deploy_frontend
      - deploy_backend
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Ansible
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      # Step 3: Run Ansible playbook with inventory file for dockercompose
      - name: Run Ansible playbook to set up ELK stack
        run: |
          ansible-playbook -i inventory.ini setup_elk.yml
      
      # Step 3: Pull and start ELK stack with Docker Compose
      - name: Start ELK stack and log server
        run: |
          docker-compose -f ./docker-compose.yml up -d


