name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    # Step 1: Checkout the code from GitHub
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install Docker Compose
    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.19.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version # Verify installation

    # Step 3: Build Docker image for Backend
    - name: Build Backend Docker image
      run: |
        cd striide-backend
        docker build -t backend-image .
        docker rmi backend-image 

    # Step 4: Build Docker image for Frontend
    - name: Build Frontend Docker image
      run: |
        cd striide-frontend
        docker build -t frontend-image .
        docker rmi frontend-image 

    # Step 5: Run Docker Compose to bring up the containers
    - name: Run Docker Compose up
      run: |
        docker-compose -f docker-compose.yml up -d

    # Step 6: Clean up Docker images
    - name: Clean up Docker images
      run: |
        docker system prune -f
